version: '3.6'

networks:
  challange-network:
    driver: bridge

services:
  challange-api:
    build: .
    volumes:
      - .:/usr/src/app
    container_name: challange-api
    environment:
      - MONGO_HOST=challange-mongo
    ports:
      - 3333:3333
    depends_on:
      - challange-mongo
    networks:
      - challange-network
    links:
      - challange-mongo

  challange-mongo:
    image: bitnami/mongodb:latest
    container_name: challange-mongo
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_USERNAME=${MONGO_USERNAME}
      - MONGODB_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_DATABASE=${MONGO_DB}
    volumes:
      - challange-mongo-data:/bitnami
    ports:
      - 27017:27017
    networks:
      - challange-network

volumes:
  challange-mongo-data:
    driver: local
